{
 "title": "HT2000",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "ht2000",
     "rawSql": "SELECT $__timeGroup(timestamp, '1m') AS time, avg(co2) AS value, min(co2) AS min, max(co2) AS max\nFROM events\nWHERE $__timeFilter(timestamp) \n  AND device = 0\nGROUP BY time"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "dataset": "ht2000",
     "rawSql": "SELECT $__timeGroup(timestamp, '1m') AS time, avg(humidity) AS value, min(humidity) AS min, max(humidity) AS max\nFROM events\nWHERE $__timeFilter(timestamp) \n  AND device = 0\nGROUP BY time"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "dataset": "ht2000",
     "rawSql": "SELECT $__timeGroup(timestamp, '1m') AS time, avg(temperature) AS value, min(temperature) AS min, max(temperature) AS max\nFROM events\nWHERE $__timeFilter(timestamp) \n  AND device = 0\nGROUP BY time"
    }
   ]
  }
 ]
}